Handling . in the app name
ServiceWeaver/weaver pull request #232
Opened 2023-04-06 18:57 UTC by myyrakle

https://github.com/ServiceWeaver/weaver/issues/113

2023-04-07 16:30 UTC, mwhittaker requested changes
Thanks for PR @myyrakle! 

I think the code&mdash;both before and after this PR&mdash;is buggy if app, deployment, or weavelet have a period in them. For example, if app is `"foo.bar"` and deployment is `"moo.cow"`, this code will parse app as `"foo.bar.moo"` and deployment as `"cow"` which is not what we want. 

I think we should either (1) restrict the set of app, deployment, and weavelet names. For example, disallow periods. Or (2), use a more sophisticated way of picking filenames. For example, serialize a proto with app, deployment, weavelet, and level and base64 encode it. 

I think (2) is overkill. We should probably do (1). The team will chat about what set of names to allow. There are some things to take into account. For example, we've recently made weavelet ids pod names, so we don't want to disallow that. 

I like your idea of fixing things in the short term though, as people are running into issues.  What do you think about revising this PR to simply replace the period separator with a hash `#`? It doesn't fundamentally solve anything, but it will help the common case until we implement a full solution. Doing nothing for now is also totally fine too :)

2023-04-07 18:29 UTC, mwhittaker commented
Ah, sorry, maybe I was unclear. I mean that instead of storing files like `app.deployment.weavelet.level.log`, we store them as `app#deployment#weavelet#level.log`.

2023-04-09 12:25 UTC, myyrakle commented
Ah, I misunderstood. I think that's fine too.

2023-04-11 00:08 UTC, mwhittaker requested changes
Thanks @myyrakle!

2023-04-11 00:08 UTC, mwhittaker commented on runtime/logging/files.go
What do you think about the following simplifications?

```diff
diff --git a/runtime/logging/files.go b/runtime/logging/files.go
index 42bbf80..02ff6a5 100644
--- a/runtime/logging/files.go
+++ b/runtime/logging/files.go
@@ -162,27 +162,17 @@ type logfile struct {
 // parseLogfile parses a logfile filename.
 func parseLogfile(filename string) (logfile, error) {
 	// TODO(mwhittaker): Ensure that apps, deployments, weavelet ids, levels
-	// don't contain a ".". Or, switch to some other delimiter that doesn't
+	// don't contain a "#". Or, switch to some other delimiter that doesn't
 	// show up.
-
-	dotParts := strings.Split(filename, ".")
-	dotPartsLen := len(dotParts)
-
-	if len(dotParts) < 2 || dotParts[dotPartsLen-1] != "log" {
-		want := "<app>#<deployment>#<weavelet>#<level>.log"
+	const want = "<app>#<deployment>#<weavelet>#<level>.log"
+	prefix, hasLogSuffix := strings.CutSuffix(filename, ".log")
+	if !hasLogSuffix {
 		return logfile{}, fmt.Errorf("filename %q must have format %q", filename, want)
 	}
-
-	noExtension := strings.Join(dotParts[0:dotPartsLen-1], ".")
-
-	parts := strings.Split(noExtension, "#")
-	partsLen := len(parts)
-
-	if partsLen != 4 {
-		want := "<app>#<deployment>#<weavelet>#<level>.log"
+	parts := strings.SplitN(prefix, "#", 4)
+	if len(parts) < 4 {
 		return logfile{}, fmt.Errorf("filename %q must have format %q", filename, want)
 	}
-
 	return logfile{
 		app:        parts[0],
 		deployment: parts[1],
```

And do you mind adding the following unit test to `files_test.go`?

```go
func TestParseLogfile(t *testing.T) {
        for _, want := range []logfile{
                // Simple strings.
                {"a", "b", "c", "d"},

                // Some empty strings.
                {"", "b", "c", "d"},
                {"a", "", "c", "d"},
                {"a", "b", "", "d"},
                {"a", "b", "c", ""},
                {"", "", "", ""},

                // Periods.
                {"a", "b.b", "c.c.c", "d.d.d.d"},

                // File suffix.
                {"log", "log", "log", "log"},
        } {
                name := filename(want.app, want.deployment, want.weavelet, want.level)
                t.Run(name, func(t *testing.T) {
                        got, err := parseLogfile(name)
                        if err != nil {
                                t.Fatalf("parseLogFile(name): %v", err)
                        }
                        if got != want {
                                t.Errorf("parseLogFile(name): got %v, want %v", got, want)
                        }
                })
        }
}
```

2023-04-11 22:39 UTC, myyrakle commented on runtime/logging/files.go
Simple and looks good to me :)

I didn't use `strings.CutSuffix` because it supports the latest version, but the minimum version of weaver is 1.20, so I knew there was no problem!

2023-04-11 22:41 UTC, myyrakle commented on runtime/logging/files.go
After reflecting the feedback again, I committed it.
Thank you for your meticulous feedback!

2023-04-11 23:23 UTC, mwhittaker reviewed
Awesome, thank you!

2023-04-11 23:23 UTC, mwhittaker approved these changes

2023-04-11 23:25 UTC, merged