implemented the solution described by @rgrandl
ServiceWeaver/weaver pull request #257
Opened 2023-04-14 10:28 UTC by naivary

I have not tested it yet but wanted get some feedback if the code already has issues that can lead to problems in the future.

2023-04-27 23:31 UTC, rgrandl requested changes
Thanks @naivary for working on this. It looks great.

2023-04-27 23:31 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +
remove empty line before checking the error. here and everywhere else

we typically do:
bla, err := ...
if err != nil {
 ....
}

2023-04-27 23:31 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +func getTmpDirs(locs []string, depId string) (map[string]string, error) {
also, move this function at the end of the file

2023-04-27 23:31 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +		}
we don't need this. Actually this leads to an error.  cmd.Output() already runs the command.

2023-04-28 22:26 UTC, naivary commented
Thanks for the great feedback. I will try to get it done by sunday.

Cheers

2023-05-01 15:33 UTC, naivary commented on internal/tool/ssh/impl/manager.go
> +	tmpDirs    map[string]string
You mean the keys should be the locations and the values the tmpdir?

2023-05-01 15:44 UTC, naivary commented
I think the naming of locs and locations is a little bit confusing. Any sugesstions for a better naming? And is it the solution you described with the comments?

Cheers.

2023-05-05 23:59 UTC, rgrandl commented
@naivary sorry for the late reply. Can you resolve the conflicts, so I can take another look? I will prioritize this as soon as you fix the conflicts.

2023-05-06 11:22 UTC, naivary commented
Got some problems with the naming because one parameter was removed. I'm trying to get it done as soon as possible.

2023-05-06 11:35 UTC, naivary commented
Now the errors should be resolved. Still the naming is confusing locs vs locations and we should discuss a better proper naming. Unfortunately I hadn't not a good idea.

Cheers.

2023-05-08 17:23 UTC, rgrandl reviewed
Looks great @naivary. Can you take a final pass on my comments? Mostly nits. Also, can you rebase again?

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +// to the given set of locations. It produces a map which
Returns the paths to the directories where the binaries were copied, keyed by locations.

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +		cmd = exec.Command("scp", ex, remotePath, loc+":"+tmpDir)
this should be `binary`. we copy the binary from the local machine (so the path should be local, as specified in the deployment). Remove `remotePath`, the remote path is simply tmpDir.

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +
remove empty line

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +
remote empty line

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +
remove empty line

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +
remove empty line

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +
remove empty line

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/deploy.go
> +// getTmpDirs prints the tmp directory in which the weaver binary will
getTmpDirs returns the path to the tmp directories where the weaver binaries will be stored at each remote location.

2023-05-08 17:23 UTC, rgrandl commented on internal/tool/ssh/impl/manager.go
> +	// keys: addresses of the locations
managed locations, and the corresponding directories to store the weaver binaries at each location

2023-05-08 17:23 UTC, rgrandl commented on remote.go
> +
remove

2023-05-08 17:23 UTC, rgrandl reviewed
Looks great @naivary. Can you take a final pass on my comments? Mostly nits. Also, can you rebase again?

2023-05-08 18:44 UTC, naivary commented
Got it done!

2023-05-08 19:57 UTC, rgrandl commented
@naivary ,can you please run ./dev/build_and_test? We have to update the doc to mention this step, probably it's not clear. Sorry about that.

2023-05-09 08:05 UTC, naivary commented
All stages were successfull!

2023-05-09 15:45 UTC, rgrandl commented
> All stages were successfull!

Great. Can you commit any new local changes after you run ./dev/build_and_test and push it again?

2023-05-10 07:48 UTC, naivary commented
There were no local changes made. I ran git add and git commit (already up to date)

2023-05-10 19:47 UTC, merged